### ISSUE TITLE
isonclust command for ONT data

### ISSUE THREAD

**Issue by marisalim** [ksahlin/isONclust#4]
Hi,

I'm testing out isONclust with my ONT data and want to verify I'm using the correct command. In the readme, it says to use IsoCon pipeline, but the biorxiv paper says you used isONclust.py. 

I got an error when I entered IsoCon pipeline (missing --fl and -outfolder vs. --outfolder), though this command seems to work:
```
isONclust --ont --fastq <my fastq file> --outfolder <output folder>
```

In addition, how can I increase the stringency for matching reads? I tried changing the --mapped_threshold parameter to 0.9, but the output was the same, so I wasn't sure whether changing from default (0.7) to 0.9 did anything. Basically, I'd like to see how read clustering performs with a range of percent similarities, say 80-90%. 

Thanks!

**Comment by marisalim** [comment]
Oops, and I should add that I am using isONclust version 0.04 on a Mac.

**Comment by ksahlin** [comment]
Oh you caught an error in the manual, will fix!

This is correct as you found:
```
isONclust --ont --fastq <my fastq file> --outfolder <output folder>
```

The parameter --mapped_threshold won't affect %-nucleotide level identity much since it relates to the percentage of the read (w.r.t. its length) that was assigned to a cluster (i.e., not related to %- nucleotide identity). 

In terms of getting "more clustering" for lower level of identity, the `--k and --w` would be the parameters to tweak. In general, lower k and w clusters more at the cost of runtime and memory usage.  The `--ont` parameter sets `--k 13 --w 20` by default. Something like `--k 12 --w [15-18]` will do more clustering, at the cost of runtime. I don't recommend `--k` below 11-12 because at that point the minimizers will not be that unique. But it also depends on how long your longest reads are. If the longest read is <15k bases, then k=11 might work well too.

**Comment by marisalim** [comment]
Great, thanks!

**Comment by marisalim** [comment]
I'm working with amplicon data so using lower k's is probably doable!

I want to double-check a few things about the output files:
- I would like to extract a representative sequence from each cluster. Does it make sense to use the reads from the 'final_cluster_origins.csv' file? Is it correct that the reads in this file have the 'largest expected number of error-free k-mers of any future read in the cluster' (from your biorxiv paper)?
- Is the 'sorted.fastq' file an intermediate output? I'm thinking it's the file that contains reads sorted by length and quality score for the clustering algorithm.
- Are the numbered output folders intermediate cluster files (e.g., 1/, 2/)?

Thanks again!

**Comment by ksahlin** [comment]
* If you work with amplicon data (primer targeted?), I can recommend our other tool [IsoCon](https://github.com/ksahlin/IsoCon). where the command would be as follows:
```
IsoCon pipeline -fl_reads <reads.fastq> -outfolder </path/to/output>
```
The reason to use IsoCon over isONclust here is that IsoCon also error corrects the reads into consensus sequences (and shows the read support for each of the consensus in a tsv file). This gives a natural way of deriving a set of consensus sequences on which phylogenies can be created. isONclust  on the other hand has no straightforward way at the moment of reconstructing a consensus from all the reads in a cluster.

* Yes, it is an intermediate output.

* Yes they are.

How many reads to you have?

**Comment by marisalim** [comment]
Yes, targeted amplicon sequencing. The datasets vary, but I may have anywhere from a few hundred (small dataset) to 10-30k (larger dataset) reads per sample.

Interesting, for IsoCon then, the final_candidates.fa are the consensus sequences?

**Comment by ksahlin** [comment]
Ok, IsoCon should be able to handle all of those sizes. Yes, the `final_candidates.fa` would be the final consensus. Yes, line counts from cluster_info.tsv is the most stable way. 

`>transcript_[id]_support_[reads supporting certain tested variant positions]_[total reads assigned to this sequence after error correction]_[if tested in final iteration]_[total reads assigned to this sequence in final output -- i.e., after statistical testinng]`

If line count is not the same as the last number there is something off, or I remember wrong and can look it up. At any rate, the line count in the tsv file is the better way to do it.

**Comment by marisalim** [comment]
Yup, most of the line counts add up correctly! There are a few transcripts with slightly different header pattern, e.g.:
`>transcript_67_support_3_6_1.749163000742186e-11_18_(I,326,1);(S,569,1)`, with 17 rows that correspond to transcript_67 and 

`>transcript_68_support_2_5_2.558106651502909e-09_18_(D,326,1);(S,570,1)`, with 6 rows that correspond to transcript_68. 

How to interpret?

**Comment by ksahlin** [comment]
I looked into this a bit more. 

The two sequences are tested against each other in the final iteration. The total number or reads supporting (i.e., assigned to) any of these two candidates at the time of the test is 18 reads (i.e., the sum of supporting reads). These two sequences are tested against each other based on two "variant positions" (the indel at pos 326, and the substitution at pos 569-570). Out of these 18 reads, 6 support the combination of variants for sequence 67 and 5 support the combination of variants for sequence 68. They both have significant p-values according to the quality values in these positions and were therefore both kept. (how much to trust quality values could be scaled down with `--max_phred_q_trusted` default is 43 (pacbio CCS) but it might make sense to do like 30 or even 25 for ONT -- this will make things less significant and reduce number of predicted sequences.  

Since some sequences will be removed through this statistical testing, the reads assigned to the removed sequences needs to find a new "host". The get reassigned through mapping to the best matching sequence. Therefore, while at the time of statistical testing there were 18 reads in total. At the time of the end of the run (after all tests) there are 17+6=23 reads supporting either of these sequences.

So indeed, counting the rows in the tsv is the only reliable way to find the final read support. And this is also the best way to post filter anything you don't believe in. Whether 3 is too few is difficult to tell, I would say that there is likely a lot that can be erroneous in that range (e.g., too confident quality values/bias in the base caller, other artifacts with the experimental protocol) but this is something that there is no clear answer to whether it is a true or erroneous sequence. It is always possible to filter sequences based on the tsv file with  a hard cutoff of minimum X supporting reads.

**Comment by marisalim** [comment]
Ah, very helpful descriptions! It definitely makes sense to lower the phred setting for ONT data. 

I have been comparing the results I get from running `isONclust --ont` vs. `IsoCon pipeline` and I usually get more reads per cluster with isONclust with slightly larger datasets (a few thousand reads). The differences were less noticeable for the small test datasets of a few hundred reads. For example, in a dataset with ~8,500 reads, ~6000 reads were clustered in the first two clusters with isONclust (~3000 reads each, and they are actually forward and reverse sequences that align reasonably well with e.g., `mafft --auto --adjustdirection`). For the same dataset with IsoCon, the largest number of reads per cluster was 162. Any idea why they differ by so much?

**Comment by ksahlin** [comment]
Because isonclust is not designed to cluster reads into different strains, it is designed to cluster similar things together in a pretty lenient way ( reads from the same gene families etc),  assuming that all sequences in an amplicon dataset are similar (?) it basically means that expected result with isonclust would just be a single cluster — which you more or less observe. This is also expected with isonclust if there are more errors than mutations. (Tell me if my assumptions about the data are incorrect)

IsoCon is being more clever with mutations. However, it may have a difficult time if the quality values are off. By lowering the threshold max qual there will be less clusters left. Also, for IsoCon it would help to orient everything in the same direction (if possible) to get more power and coverage per consensus.

What is the expected amount of clusters? And what does a cluster represent?

**Comment by marisalim** [comment]
Ok, then it seems that isonclust is best for our current datasets. This is DNA barcoding data, so there should be 1 cluster with the majority of reads because they come from the same sample. Reads that fall in other smaller clusters could be e.g., bleedthrough from other multiplexed samples, reads with high sequencing error (single sample, so yes, errors not mutations), or low-level contaminants that get amplified from the DNA extraction (e.g., bacteria, etc.). Eventually, we'll be working with mixed species samples, for which there should be a bunch of clusters that represent different species. I'm using this read clustering approach because the ONT data have high error rate so the clustering step helps to get cleaner consensus sequences.

**Comment by ksahlin** [comment]
Oh, Okay. Yes, running e.g., [spoa](https://github.com/rvaser/spoa) on the sequences in a cluster should give a very good consensus sequence given that the sequences do not have larger  structural differences (e.g., due to alternative splicing in the transcript data case).

**Comment by marisalim** [comment]
Great, I will check out spoa. Thanks for your help!

**Comment by ksahlin** [comment]
Anytime! Feel free to let me know how it goes and if you run into any problems.

**Comment by marisalim** [comment]
Thanks, it's working great so far!

**Comment by marisalim** [comment]
Hi again,

For the isONclust output file, what are the last 2 values in the final_cluster_origins.csv file?

Read cluster ID | read name |sequence | quality scores |? | ?
--- | --- |---|---|---|---|

Thanks!

**Comment by ksahlin** [comment]
The first one is expected number of error free kmers in the read (based on quality values). The second one is inferred reads error rate after homopolymer compression (inferred by looking at the average base error probabilities after homopolymer compression).

**Comment by marisalim** [comment]
Ah, ok. Thanks!
